export const ACTIVITY_TYPES = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  PROFILE_UPDATED: "PROFILE_UPDATED",

  USER_ACTIVATED: "USER_ACTIVATED",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",

  TASK_CREATED: "TASK_CREATED",
  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_REASSIGNED: "TASK_REASSIGNED",
  TASK_STATUS_CHANGED: "TASK_STATUS_CHANGED",
  TASK_COMPLETED: "TASK_COMPLETED",

  SUBTASK_CREATED: "SUBTASK_CREATED",
  SUBTASK_COMPLETED: "SUBTASK_COMPLETED",

  AI_BREAKDOWN_REQUESTED: "AI_BREAKDOWN_REQUESTED",
  AI_BREAKDOWN_COMPLETED: "AI_BREAKDOWN_COMPLETED",
  AI_QUOTA_EXCEEDED: "AI_QUOTA_EXCEEDED"
} as const

export type ActivityType =
  typeof ACTIVITY_TYPES[keyof typeof ACTIVITY_TYPES]
